### YamlMime:FAQ
metadata:
  title: Merkezi Dağıtım SSS
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: faq
  ms.service: microsoft-365-business
  ms.localizationpriority: medium
  ms.collection:
  - Tier2
  - scotvorg
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  - Adm_TOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: Microsoft 365 yönetim merkezi Merkezi Dağıtım hakkındaki sık sorulan soruların yanıtlarını gözden geçirin.
  ms.openlocfilehash: 3cdc452c532153eff5969888f36a38415e850214
  ms.sourcegitcommit: 181a0aff54842dcbafd834647c6e9ee47304d10f
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 10/27/2022
  ms.locfileid: "68731909"
title: Merkezi Dağıtım SSS
summary: Merkezi Dağıtım, bir Office 365 yöneticisinin kuruluştaki kullanıcılara ve gruplara Office Eklentileri (Word, Excel, PowerPoint ve Outlook) dağıtması için önerilen yoldur. Kuruluş, bu makalede açıklandığı gibi Merkezi Dağıtım'ı kullanmaya yönelik tüm gereksinimleri karşılar.
sections:
- name: Yok sayıldı
  questions:
  - question: >
      Kuruluşumun Merkezi Dağıtım için ayarlandığını Nasıl yaparım? biliyor musunuz?
    answer: "Eklentilerin merkezi dağıtımı, kullanıcıların Kurumlar için Microsoft 365 Uygulamaları kullanmasını (ve kuruluş oturum açma kimlik bilgilerini kullanarak Office'te oturum açmasını) ve Exchange Online posta kutularına sahip olmasını gerektirir. Abonelik dizininizin Azure Active Directory'de veya federasyonda olması gerekir. \n \nMerkezi Dağıtım yalnızca çevrimiçi posta kutuları için desteklenir. Şirket içi Exchange posta kutularına dağıtımı desteklemez.\n\nAboneliğinizin uygun olup olmadığını belirlemek için [Merkezi Dağıtım Uyumluluk Denetleyicisi'ni](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) kullanabilirsiniz. \n  \n"
  - question: >
      Merkezi Dağıtım ile eklenti kullanıcı atamalarını nasıl hedefleyebilirsiniz?
    answer: "Merkezi Dağıtım tek tek kullanıcılara, gruplara ve kiracıdaki herkese atamaları destekler. Merkezi Dağıtım, üst düzey gruplardaki veya üst grubu olmayan gruplardaki kullanıcılar için kullanılabilir, ancak iç içe gruplardaki veya üst grupları olan gruplardaki kullanıcılar için kullanılamaz. Merkezi Dağıtım ayrıca Office 365 Grupları, dağıtım listeleri, dinamik gruplar ve güvenlik grupları da dahil olmak üzere çoğu Azure Active Directory grubunun bir parçasıdır. \n\nDaha kolay yönetim için tek tek kullanıcı ataması yerine grup atamalarını kullanmak daha iyidir.\n \nDiğer ayrıntılar için bkz. [Kullanıcı ve Grup atamaları](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: >
      Eklentilerin tüm kullanıcılar için görünmesi ne kadar sürer?
    answer: >
      Yeni bir eklenti dağıtımının tüm kullanıcılara gösterilmesi 24 saat kadar sürebilir. Eklenti güncelleştirmeleri, açma veya kapatma değişikliklerinin kullanıcılar için yansıtılmış olması 72 saate kadar sürebilir.
  - question: "Eklentilerin tüm kullanıcılar için kaldırılması ne kadar sürer?    \n"
    answer: >
      Eklenti kaldırma işleminin tüm kullanıcılar için yansıtılması 24 saat kadar sürebilir.
  - question: >
      Yönetici olarak, kuruluşum için eklentilere kullanıcı erişimini nasıl yönetebilirim?
    answer: >
      Eklentilerin kullanıcılara, gruplara veya kuruluşunuzun tamamına kolay dağıtımı için yöneticilerin Merkezi Dağıtım'ı kullanmasını öneririz.


      Kullanıcı erişimini yönetme hakkında daha fazla bilgi için bkz:
       - [Tüm istemcilerde Office Mağazası'nı kapatarak eklenti indirmelerini engelleme (Outlook dışında)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Outlook için eklentileri yükleyebilecek ve yönetebilecek yöneticileri ve kullanıcıları belirtin](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "Merkezi Dağıtım, yöneticilere Outlook eklentileri için dağıtım yöntemini seçme esnekliği sağlayacak mı? \n"
    answer: "Evet. Merkezi Dağıtım, yöneticilere eklenti dağıtımı sırasında Outlook eklentileri için üç dağıtım yönteminden birini seçme esnekliği sağlar:\n         \n**Sabit** Eklenti, atanan kullanıcılara otomatik olarak dağıtılır ve eklentiyi şeritlerinden kaldıramaz.\n\n**Kullanılabilir** Kullanıcılar **Outlook'ta Giriş > Daha Fazla Eklenti Al > Yönetici yönetilen eklentiler'i seçerek eklentiyi** yükleyebilir.\n \n**Isteğe bağlı** Eklenti, atanan kullanıcılara otomatik olarak dağıtılır, ancak kaldırmayı seçebilirler.\n>[!NOTE]\n>Tümleşik Uygulamalar bu seçeneğe sahip değildir; ancak, yöneticiler bunu **Ayarlar** > **Tümleşik Uygulamalar'ın** altında gerçekleştirmek ve eklenti bağlantısını seçmek için eski **Eklenti** sayfasını kullanmaya devam edebilir.\n:::image type=\"content\" source=\"../../media/addin-links.png\" alt-text=\"Raporlar'daki Benimseme Puanı sayfası.\" lightbox=\"../../media/addin-links.png\":::  \n"
  - question: "Yöneticiler İş Kolu (LOB) eklentilerini güncelleştirebilir mi? \n"
    answer: "Evet. Yöneticiler, yönetici tarafından dağıtılan LOB eklentileri için meta veri değişikliklerini desteklemek üzere yeni bir bildirim dosyası yükleyebilir. Eklenti, Office uygulamalarının bir sonraki başlatışında güncelleştirilir. Web uygulaması her an değişebilir.\n \nDaha fazla bilgi için bkz. [iş kolu eklentisi](./manage-addins-in-the-admin-center.md).  \n"
  - question: "Yöneticiler eklentileri kapatabilir mi? \n"
    answer: >
      Evet. Yöneticiler, Microsoft yönetim merkezinden tüm kullanıcılar için dağıttığı eklentileri açabilir veya kapatabilir.


      Daha fazla bilgi için bkz [. Eklenti durumları](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      Yöneticiler eklentileri silebilir veya kaldırabilir mi?
    answer: "Evet. Yöneticiler, tüm kullanıcılar için dağıtılan eklentileri Microsoft yönetim merkezinden silebilir.\n\nDaha fazla bilgi için bkz. [Eklentiyi silme](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "Yöneticiler Merkezi Dağıtım'ı kullanarak Office Mağazası'ndan ücretli eklentiler dağıtabilir mi? \n"
    answer: "Hayır. Şu anda Merkezi Dağıtım'ı kullanarak Office Mağazası'ndan ücretli eklentiler dağıtamazsınız. \n \nBildirim dosyası veya URL istemek için ücretli eklenti için ISV Geliştiricisi'ne ulaşmanızı öneririz. Kiracı yöneticisi daha sonra Merkezi Dağıtım'ı kullanarak eklentiyi LOB eklentisi olarak dağıtabilir.\n   \n"
  - question: "Kuruluşum için eklentileri yönetmek için hangi yönetici rolüne ihtiyacım var? \n"
    answer: "Genel Yönetici, eklenti yönetimi yaşam döngüsüne tam erişime sahip önerilen roldür. Microsoft 365 İş aboneliğinizi satın alan kişi sizseniz Genel yönetici olursunuz.\n\nAboneliğiniz, kuruluşunuzdaki diğer kullanıcılara atayabileceğiniz bir dizi yönetici rolüyle birlikte gelir. Her yönetici rolü ortak iş işlevlerine eşler ve kuruluşunuzdaki kişilere Microsoft 365 yönetim merkezi belirli görevleri gerçekleştirme izinleri verir.  \n \nDaha fazla bilgi için bkz. [Yönetici rolleri atama](../add-users/assign-admin-roles.md?view=o365-worldwide).\n   \n"
  - question: >
      Kaç eklenti dağıtabilirim?
    answer: Kiracılarındaki yöneticiler tarafından toplam 200 Excel, Outlook, PowerPoint ve Word eklentisi dağıtılabilir.
