### YamlMime:FAQ
metadata:
  title: Merkezi Dağıtım SSS
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: faq
  ms.service: o365-administration
  ms.localizationpriority: medium
  ms.collection:
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  - Adm_TOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: Microsoft 365 yönetim merkezi Merkezi Dağıtım hakkındaki sık sorulan soruların yanıtlarını gözden geçirin.
  ms.openlocfilehash: 870e59a96f1dee5e56b130f7750faa0addd593c9
  ms.sourcegitcommit: 45bc65972d4007b2aa7760d4457a0d2699f81926
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 04/20/2022
  ms.locfileid: "64971097"
title: Merkezi Dağıtım SSS
summary: Merkezi Dağıtım, bir Office 365 yöneticisinin kuruluştaki kullanıcılara ve gruplara Office eklentileri (Word, Excel, PowerPoint ve Outlook) dağıtması için önerilen yoldur. Kuruluş, bu makalede açıklandığı gibi Merkezi Dağıtım'ı kullanmaya yönelik tüm gereksinimleri karşılar.
sections:
- name: Yok sayıldı
  questions:
  - question: >
      Kuruluşumun Merkezi Dağıtım için ayarlandığını Nasıl yaparım? biliyor musunuz?
    answer: "Eklentilerin merkezi dağıtımı, kullanıcıların Kurumlar için Microsoft 365 Uygulamaları kullanmasını (ve kuruluş oturum açma kimlik bilgilerini kullanarak Office oturum açmasını) ve Exchange Online posta kutularına sahip olmasını gerektirir. Abonelik dizininizin Azure Active Directory içinde veya federasyonda olması gerekir. \n \nMerkezi Dağıtım yalnızca çevrimiçi posta kutuları için desteklenir. Şirket içi Exchange posta kutularına dağıtımı desteklemez.\n\nAboneliğinizin uygun olup olmadığını belirlemek için [Merkezi Dağıtım Uyumluluk Denetleyicisi'ni](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) kullanabilirsiniz. \n  \n"
  - question: >
      Merkezi Dağıtım ile eklenti kullanıcı atamalarını nasıl hedefleyebilirsiniz?
    answer: "Merkezi Dağıtım tek tek kullanıcılara, gruplara ve kiracıdaki herkese atamaları destekler. Merkezi Dağıtım, üst düzey gruplardaki veya üst grubu olmayan gruplardaki kullanıcılar için kullanılabilir, ancak iç içe gruplardaki veya üst grupları olan gruplardaki kullanıcılar için kullanılamaz. Merkezi Dağıtım ayrıca Office 365 Grupları, dağıtım listeleri ve güvenlik grupları da dahil olmak üzere çoğu Azure Active Directory grubunun bir parçasıdır. \n\nDaha kolay yönetim için tek tek kullanıcı ataması yerine grup atamalarını kullanmak daha iyidir.\n \nDiğer ayrıntılar için bkz. [Kullanıcı ve Grup atamaları](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: >
      Eklentilerin tüm kullanıcılar için görünmesi ne kadar sürer?
    answer: >
      Yeni bir eklenti dağıtımının tüm kullanıcılara gösterilmesi 24 saat kadar sürebilir. Eklenti güncelleştirmelerinin, açma veya kapatmadaki değişikliklerin veya eklenti kaldırmaların kullanıcılara yansıtılması 72 saate kadar sürebilir.
  - question: >
      Yönetici olarak, kuruluşum için eklentilere kullanıcı erişimini nasıl yönetebilirim?
    answer: >
      Eklentilerin kullanıcılara, gruplara veya kuruluşunuzun tamamına kolay dağıtımı için yöneticilerin Merkezi Dağıtım'ı kullanmasını öneririz.


      Kullanıcı erişimini yönetme hakkında daha fazla bilgi için bkz:
       - [tüm istemcilerde Office Mağazası'nı kapatarak eklenti indirmelerini engelleme (Outlook hariç)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Outlook için eklentileri yükleyebilecek ve yönetebilecek yöneticileri ve kullanıcıları belirtin](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "Merkezi Dağıtım, yöneticilere Outlook eklentilerin dağıtım yöntemini seçme esnekliği sağlayacak mı? \n"
    answer: "Evet. Merkezi Dağıtım, yöneticilere eklenti dağıtımı sırasında Outlook eklentileri için iki dağıtım yönteminden birini seçme esnekliği sağlar:\n         \n**Kullanılabilir** Kullanıcılar, **Giriş > Yönetici tarafından yönetilen > Daha Fazla Eklenti Al'ı seçerek eklentiyi Outlook** yükleyebilir.\n \n**Isteğe bağlı** Eklenti, atanan kullanıcılara otomatik olarak dağıtılır, ancak kaldırmayı seçebilirler.\n    \n"
  - question: "Yöneticiler İş Kolu (LOB) eklentilerini güncelleştirebilir mi? \n"
    answer: "Evet. Yöneticiler, yönetici tarafından dağıtılan LOB eklentileri için meta veri değişikliklerini desteklemek üzere yeni bir bildirim dosyası yükleyebilir. Eklenti, Office uygulamaları bir sonraki başlatışında güncelleştirilir. Web uygulaması her an değişebilir.\n \nDaha fazla bilgi için bkz. [iş kolu eklentisi](./manage-addins-in-the-admin-center.md).  \n"
  - question: "Yöneticiler eklentileri kapatabilir mi? \n"
    answer: >
      Evet. Yöneticiler, Microsoft yönetim merkezinden tüm kullanıcılar için dağıttığı eklentileri açabilir veya kapatabilir.


      Daha fazla bilgi için bkz [. Eklenti durumları](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      Yöneticiler eklentileri silebilir veya kaldırabilir mi?
    answer: "Evet. Yöneticiler, tüm kullanıcılar için dağıtılan eklentileri Microsoft yönetim merkezinden silebilir.\n\nDaha fazla bilgi için bkz. [Eklentiyi silme](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "Yöneticiler, Merkezi Dağıtım'ı kullanarak ücretli eklentileri Office Mağazası'ndan dağıtabilir mi? \n"
    answer: "Hayır. Şu anda Merkezi Dağıtım'ı kullanarak ücretli eklentileri Office Store'dan dağıtamazsınız. \n \nBildirim dosyası veya URL istemek için ücretli eklenti için ISV Geliştiricisi'ne ulaşmanızı öneririz. Kiracı yöneticisi daha sonra Merkezi Dağıtım'ı kullanarak eklentiyi LOB eklentisi olarak dağıtabilir.\n   \n"
  - question: "Kuruluşum için eklentileri yönetmek için hangi yönetici rolüne ihtiyacım var? \n"
    answer: "Genel Yönetici, eklenti yönetimi yaşam döngüsüne tam erişime sahip önerilen roldür. Microsoft 365 İş aboneliğinizi satın alan kişi sizseniz Genel yönetici olursunuz.\n\nAboneliğiniz, kuruluşunuzdaki diğer kullanıcılara atayabileceğiniz bir dizi yönetici rolüyle birlikte gelir. Her yönetici rolü ortak iş işlevlerine eşler ve kuruluşunuzdaki kişilere Microsoft 365 yönetim merkezi belirli görevleri gerçekleştirme izinleri verir.  \n \nDaha fazla bilgi için bkz. [Yönetici rolleri atama](../add-users/assign-admin-roles.md?view=o365-worldwide)."
